// Enhanced player data with comprehensive match stats
export const enhancedPlayers = {
  team_a: {
    1: {
      name: "Harry Kane",
      rating: 8.2,
      position: "ST",
      preferredPositions: ["ST", "CF"],
      goals: 1,
      assists: 0,
      shots: 4,
      shotsOnTarget: 2,
      passes: 32,
      passAccuracy: 85,
      tackles: 1,
      interceptions: 2,
      fouls: 2,
      minutes: 90,
      fitness: 92,
      form: 8.1,
    },
    2: {
      name: "Kevin De Bruyne",
      rating: 8.0,
      position: "CAM",
      preferredPositions: ["CAM", "CM", "RW"],
      goals: 0,
      assists: 2,
      shots: 3,
      shotsOnTarget: 1,
      passes: 78,
      passAccuracy: 92,
      keyPasses: 6,
      tackles: 3,
      interceptions: 4,
      minutes: 90,
      fitness: 88,
      form: 8.3,
    },
    3: {
      name: "Virgil van Dijk",
      rating: 7.9,
      position: "CB",
      preferredPositions: ["CB"],
      goals: 0,
      assists: 0,
      passes: 65,
      passAccuracy: 94,
      tackles: 4,
      interceptions: 7,
      clearances: 12,
      aerialDuels: 8,
      minutes: 90,
      fitness: 95,
      form: 7.8,
    },
    4: {
      name: "Alisson Becker",
      rating: 7.8,
      position: "GK",
      preferredPositions: ["GK"],
      goals: 0,
      assists: 0,
      saves: 5,
      cleanSheets: 0,
      punches: 2,
      catches: 3,
      goalsConceded: 1,
      minutes: 90,
      fitness: 96,
      form: 7.9,
    },
    5: {
      name: "Trent Alexander-Arnold",
      rating: 7.7,
      position: "RB",
      preferredPositions: ["RB", "RWB"],
      goals: 0,
      assists: 1,
      passes: 89,
      passAccuracy: 88,
      crosses: 12,
      keyPasses: 4,
      tackles: 5,
      interceptions: 3,
      minutes: 90,
      fitness: 86,
      form: 7.6,
    },
    6: {
      name: "Rodri",
      rating: 7.8,
      position: "CDM",
      preferredPositions: ["CDM", "CM"],
      goals: 0,
      assists: 0,
      passes: 95,
      passAccuracy: 96,
      tackles: 6,
      interceptions: 5,
      duels: 12,
      minutes: 90,
      fitness: 94,
      form: 7.9,
    },
    7: {
      name: "Son Heung-min",
      rating: 7.9,
      position: "LW",
      preferredPositions: ["LW", "RW", "ST"],
      goals: 1,
      assists: 0,
      shots: 5,
      shotsOnTarget: 3,
      passes: 28,
      passAccuracy: 82,
      dribbles: 7,
      minutes: 90,
      fitness: 89,
      form: 8.0,
    },
    8: {
      name: "Joshua Kimmich",
      rating: 7.7,
      position: "CM",
      preferredPositions: ["CM", "CDM", "RB"],
      goals: 0,
      assists: 0,
      passes: 87,
      passAccuracy: 91,
      tackles: 4,
      interceptions: 6,
      minutes: 67,
      fitness: 85,
      form: 7.6,
    },
    9: {
      name: "Ruben Dias",
      rating: 7.6,
      position: "CB",
      preferredPositions: ["CB"],
      goals: 0,
      assists: 0,
      passes: 54,
      passAccuracy: 93,
      tackles: 3,
      interceptions: 5,
      clearances: 8,
      minutes: 90,
      fitness: 93,
      form: 7.5,
    },
    10: {
      name: "Ederson",
      rating: 7.5,
      position: "GK",
      preferredPositions: ["GK"],
      goals: 0,
      assists: 0,
      saves: 0,
      cleanSheets: 0,
      goalsConceded: 0,
      minutes: 0,
      fitness: 100,
      form: 7.4,
    },
    11: {
      name: "Phil Foden",
      rating: 7.8,
      position: "RW",
      preferredPositions: ["RW", "CAM", "LW"],
      goals: 0,
      assists: 0,
      shots: 2,
      shotsOnTarget: 1,
      passes: 41,
      passAccuracy: 87,
      dribbles: 5,
      minutes: 45,
      fitness: 84,
      form: 7.7,
    },
    23: {
      name: "Bukayo Saka",
      rating: 7.6,
      position: "RW",
      preferredPositions: ["RW", "LW", "RWB"],
      goals: 0,
      assists: 1,
      shots: 3,
      shotsOnTarget: 2,
      passes: 29,
      passAccuracy: 84,
      dribbles: 4,
      minutes: 45,
      fitness: 87,
      form: 7.8,
    },
    24: {
      name: "Declan Rice",
      rating: 7.5,
      position: "CDM",
      preferredPositions: ["CDM", "CM"],
      goals: 0,
      assists: 0,
      passes: 42,
      passAccuracy: 89,
      tackles: 3,
      interceptions: 4,
      minutes: 23,
      fitness: 88,
      form: 7.4,
    },
    25: {
      name: "Kyle Walker",
      rating: 7.4,
      position: "RB",
      preferredPositions: ["RB", "CB"],
      goals: 0,
      assists: 0,
      passes: 0,
      passAccuracy: 0,
      tackles: 0,
      interceptions: 0,
      minutes: 0,
      fitness: 100,
      form: 7.3,
    },
    26: {
      name: "John Stones",
      rating: 7.3,
      position: "CB",
      preferredPositions: ["CB", "CDM"],
      goals: 0,
      assists: 0,
      passes: 0,
      passAccuracy: 0,
      tackles: 0,
      interceptions: 0,
      minutes: 0,
      fitness: 100,
      form: 7.2,
    },
    27: {
      name: "Jack Grealish",
      rating: 7.2,
      position: "LW",
      preferredPositions: ["LW", "CAM"],
      goals: 0,
      assists: 0,
      passes: 0,
      passAccuracy: 0,
      dribbles: 0,
      minutes: 0,
      fitness: 100,
      form: 7.1,
    },
  },
  team_b: {
    12: {
      name: "Kylian Mbappé",
      rating: 8.3,
      position: "ST",
      preferredPositions: ["ST", "LW"],
      goals: 1,
      assists: 0,
      shots: 6,
      shotsOnTarget: 4,
      passes: 24,
      passAccuracy: 79,
      dribbles: 9,
      minutes: 90,
      fitness: 91,
      form: 8.4,
    },
    13: {
      name: "Erling Haaland",
      rating: 8.1,
      position: "ST",
      preferredPositions: ["ST"],
      goals: 0,
      assists: 0,
      shots: 5,
      shotsOnTarget: 3,
      passes: 18,
      passAccuracy: 76,
      aerialDuels: 7,
      minutes: 67,
      fitness: 87,
      form: 8.0,
    },
    14: {
      name: "Lionel Messi",
      rating: 8.0,
      position: "RW",
      preferredPositions: ["RW", "CAM", "ST"],
      goals: 0,
      assists: 1,
      shots: 4,
      shotsOnTarget: 2,
      passes: 52,
      passAccuracy: 90,
      keyPasses: 5,
      dribbles: 8,
      minutes: 90,
      fitness: 82,
      form: 8.1,
    },
    15: {
      name: "N'Golo Kanté",
      rating: 7.8,
      position: "CDM",
      preferredPositions: ["CDM", "CM"],
      goals: 0,
      assists: 0,
      passes: 67,
      passAccuracy: 89,
      tackles: 8,
      interceptions: 9,
      minutes: 90,
      fitness: 86,
      form: 7.9,
    },
    16: {
      name: "Marquinhos",
      rating: 7.7,
      position: "CB",
      preferredPositions: ["CB"],
      goals: 0,
      assists: 0,
      passes: 58,
      passAccuracy: 92,
      tackles: 5,
      interceptions: 6,
      clearances: 10,
      minutes: 90,
      fitness: 94,
      form: 7.6,
    },
    17: {
      name: "Manuel Neuer",
      rating: 7.6,
      position: "GK",
      preferredPositions: ["GK"],
      goals: 0,
      assists: 0,
      saves: 4,
      cleanSheets: 0,
      punches: 1,
      catches: 2,
      goalsConceded: 2,
      minutes: 90,
      fitness: 88,
      form: 7.7,
    },
    18: {
      name: "Achraf Hakimi",
      rating: 7.7,
      position: "RB",
      preferredPositions: ["RB", "RWB"],
      goals: 0,
      assists: 0,
      passes: 45,
      passAccuracy: 86,
      crosses: 8,
      tackles: 4,
      interceptions: 3,
      minutes: 90,
      fitness: 89,
      form: 7.6,
    },
    19: {
      name: "Federico Valverde",
      rating: 7.6,
      position: "CM",
      preferredPositions: ["CM", "RM", "CDM"],
      goals: 0,
      assists: 0,
      passes: 72,
      passAccuracy: 88,
      tackles: 5,
      interceptions: 4,
      shots: 2,
      minutes: 90,
      fitness: 92,
      form: 7.5,
    },
    20: {
      name: "Theo Hernandez",
      rating: 7.5,
      position: "LB",
      preferredPositions: ["LB", "LWB"],
      goals: 0,
      assists: 0,
      passes: 49,
      passAccuracy: 84,
      crosses: 7,
      tackles: 3,
      interceptions: 2,
      minutes: 82,
      fitness: 85,
      form: 7.4,
    },
    21: {
      name: "Jan Oblak",
      rating: 7.4,
      position: "GK",
      preferredPositions: ["GK"],
      goals: 0,
      assists: 0,
      saves: 0,
      cleanSheets: 0,
      goalsConceded: 0,
      minutes: 0,
      fitness: 100,
      form: 7.3,
    },
    22: {
      name: "Luis Diaz",
      rating: 7.7,
      position: "LW",
      preferredPositions: ["LW", "RW"],
      goals: 0,
      assists: 0,
      shots: 3,
      shotsOnTarget: 2,
      passes: 26,
      passAccuracy: 81,
      dribbles: 6,
      minutes: 0,
      fitness: 100,
      form: 7.6,
    },
    28: {
      name: "Karim Benzema",
      rating: 7.9,
      position: "ST",
      preferredPositions: ["ST", "CF"],
      goals: 0,
      assists: 0,
      shots: 2,
      shotsOnTarget: 1,
      passes: 14,
      passAccuracy: 78,
      minutes: 23,
      fitness: 83,
      form: 7.8,
    },
    29: {
      name: "Luka Modric",
      rating: 7.8,
      position: "CM",
      preferredPositions: ["CM", "CAM"],
      goals: 0,
      assists: 0,
      passes: 0,
      passAccuracy: 0,
      tackles: 0,
      interceptions: 0,
      minutes: 0,
      fitness: 100,
      form: 7.7,
    },
    30: {
      name: "Antonio Rudiger",
      rating: 7.4,
      position: "CB",
      preferredPositions: ["CB"],
      goals: 0,
      assists: 0,
      passes: 0,
      passAccuracy: 0,
      tackles: 0,
      interceptions: 0,
      minutes: 0,
      fitness: 100,
      form: 7.3,
    },
    31: {
      name: "Vinicius Junior",
      rating: 7.9,
      position: "LW",
      preferredPositions: ["LW", "RW"],
      goals: 0,
      assists: 0,
      passes: 0,
      passAccuracy: 0,
      dribbles: 0,
      minutes: 0,
      fitness: 100,
      form: 7.8,
    },
    32: {
      name: "Thibaut Courtois",
      rating: 7.5,
      position: "GK",
      preferredPositions: ["GK"],
      goals: 0,
      assists: 0,
      saves: 0,
      cleanSheets: 0,
      goalsConceded: 0,
      minutes: 0,
      fitness: 100,
      form: 7.4,
    },
  },
};

// Initial lineups data
export const initialLineups = {
  team_a: [
    {
      id: 1,
      name: "Harry Kane",
      position: "ST",
      preferredPositions: ["ST", "CF"],
      number: 9,
      is_captain: true,
      stats: { goals: 0, assists: 0, minutes: 0, shots: 0, passes: 0 },
    },
    {
      id: 2,
      name: "Kevin De Bruyne",
      position: "CAM",
      preferredPositions: ["CAM", "CM", "RW"],
      number: 17,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, shots: 0, passes: 0 },
    },
    {
      id: 3,
      name: "Virgil van Dijk",
      position: "CB",
      preferredPositions: ["CB"],
      number: 4,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, tackles: 0, interceptions: 0 },
    },
    {
      id: 4,
      name: "Alisson Becker",
      position: "GK",
      preferredPositions: ["GK"],
      number: 1,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, saves: 0, cleanSheets: 0 },
    },
    {
      id: 5,
      name: "Trent Alexander-Arnold",
      position: "RB",
      preferredPositions: ["RB", "RWB"],
      number: 66,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, crosses: 0, tackles: 0 },
    },
    {
      id: 6,
      name: "Rodri",
      position: "CDM",
      preferredPositions: ["CDM", "CM"],
      number: 16,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, passes: 0, tackles: 0 },
    },
    {
      id: 7,
      name: "Son Heung-min",
      position: "LW",
      preferredPositions: ["LW", "RW", "ST"],
      number: 7,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, shots: 0, dribbles: 0 },
    },
    {
      id: 8,
      name: "Joshua Kimmich",
      position: "CM",
      preferredPositions: ["CM", "CDM", "RB"],
      number: 6,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, passes: 0, interceptions: 0 },
    },
    {
      id: 9,
      name: "Ruben Dias",
      position: "CB",
      preferredPositions: ["CB"],
      number: 3,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, tackles: 0, clearances: 0 },
    },
    {
      id: 10,
      name: "Ederson",
      position: "GK",
      preferredPositions: ["GK"],
      number: 31,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, saves: 0, cleanSheets: 0 },
    },
    {
      id: 11,
      name: "Phil Foden",
      position: "RW",
      preferredPositions: ["RW", "CAM", "LW"],
      number: 47,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, shots: 0, dribbles: 0 },
    },
  ],
  team_b: [
    {
      id: 12,
      name: "Kylian Mbappé",
      position: "ST",
      preferredPositions: ["ST", "LW"],
      number: 7,
      is_captain: true,
      stats: { goals: 0, assists: 0, minutes: 0, shots: 0, dribbles: 0 },
    },
    {
      id: 13,
      name: "Erling Haaland",
      position: "ST",
      preferredPositions: ["ST"],
      number: 9,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, shots: 0, aerialDuels: 0 },
    },
    {
      id: 14,
      name: "Lionel Messi",
      position: "RW",
      preferredPositions: ["RW", "CAM", "ST"],
      number: 10,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, shots: 0, keyPasses: 0 },
    },
    {
      id: 15,
      name: "N'Golo Kanté",
      position: "CDM",
      preferredPositions: ["CDM", "CM"],
      number: 13,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, tackles: 0, interceptions: 0 },
    },
    {
      id: 16,
      name: "Marquinhos",
      position: "CB",
      preferredPositions: ["CB"],
      number: 5,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, tackles: 0, clearances: 0 },
    },
    {
      id: 17,
      name: "Manuel Neuer",
      position: "GK",
      preferredPositions: ["GK"],
      number: 1,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, saves: 0, cleanSheets: 0 },
    },
    {
      id: 18,
      name: "Achraf Hakimi",
      position: "RB",
      preferredPositions: ["RB", "RWB"],
      number: 2,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, crosses: 0, tackles: 0 },
    },
    {
      id: 19,
      name: "Federico Valverde",
      position: "CM",
      preferredPositions: ["CM", "RM", "CDM"],
      number: 15,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, passes: 0, tackles: 0 },
    },
    {
      id: 20,
      name: "Theo Hernandez",
      position: "LB",
      preferredPositions: ["LB", "LWB"],
      number: 21,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, crosses: 0, tackles: 0 },
    },
    {
      id: 21,
      name: "Jan Oblak",
      position: "GK",
      preferredPositions: ["GK"],
      number: 13,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, saves: 0, cleanSheets: 0 },
    },
    {
      id: 22,
      name: "Luis Diaz",
      position: "LW",
      preferredPositions: ["LW", "RW"],
      number: 23,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, shots: 0, dribbles: 0 },
    },
  ],
};

// Initial substitutes data
export const initialSubstitutes = {
  team_a: [
    {
      id: 23,
      name: "Bukayo Saka",
      position: "RW",
      preferredPositions: ["RW", "LW", "RWB"],
      number: 7,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, shots: 0, dribbles: 0 },
    },
    {
      id: 24,
      name: "Declan Rice",
      position: "CDM",
      preferredPositions: ["CDM", "CM"],
      number: 41,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, passes: 0, tackles: 0 },
    },
    {
      id: 25,
      name: "Kyle Walker",
      position: "RB",
      preferredPositions: ["RB", "CB"],
      number: 2,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, tackles: 0, interceptions: 0 },
    },
    {
      id: 26,
      name: "John Stones",
      position: "CB",
      preferredPositions: ["CB", "CDM"],
      number: 5,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, tackles: 0, clearances: 0 },
    },
    {
      id: 27,
      name: "Jack Grealish",
      position: "LW",
      preferredPositions: ["LW", "CAM"],
      number: 10,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, dribbles: 0, passes: 0 },
    },
  ],
  team_b: [
    {
      id: 28,
      name: "Karim Benzema",
      position: "ST",
      preferredPositions: ["ST", "CF"],
      number: 19,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, shots: 0, passes: 0 },
    },
    {
      id: 29,
      name: "Luka Modric",
      position: "CM",
      preferredPositions: ["CM", "CAM"],
      number: 10,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, passes: 0, tackles: 0 },
    },
    {
      id: 30,
      name: "Antonio Rudiger",
      position: "CB",
      preferredPositions: ["CB"],
      number: 22,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, tackles: 0, clearances: 0 },
    },
    {
      id: 31,
      name: "Vinicius Junior",
      position: "LW",
      preferredPositions: ["LW", "RW"],
      number: 20,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, dribbles: 0, shots: 0 },
    },
    {
      id: 32,
      name: "Thibaut Courtois",
      position: "GK",
      preferredPositions: ["GK"],
      number: 1,
      is_captain: false,
      stats: { goals: 0, assists: 0, minutes: 0, saves: 0, cleanSheets: 0 },
    },
  ],
};

// Formation positions data
export const formationPositions = {
  "4-3-3": [
    { id: "GK", x: 50, y: 95, label: "GK" },
    { id: "RB", x: 20, y: 75, label: "RB" },
    { id: "CB", x: 35, y: 75, label: "CB" },
    { id: "CB", x: 65, y: 75, label: "CB" },
    { id: "LB", x: 80, y: 75, label: "LB" },
    { id: "CDM", x: 50, y: 65, label: "CDM" },
    { id: "CM", x: 35, y: 55, label: "CM" },
    { id: "CM", x: 65, y: 55, label: "CM" },
    { id: "RW", x: 20, y: 35, label: "RW" },
    { id: "ST", x: 50, y: 25, label: "ST" },
    { id: "LW", x: 80, y: 35, label: "LW" },
  ],
  "4-4-2": [
    { id: "GK", x: 50, y: 95, label: "GK" },
    { id: "RB", x: 20, y: 75, label: "RB" },
    { id: "CB", x: 35, y: 75, label: "CB" },
    { id: "CB", x: 65, y: 75, label: "CB" },
    { id: "LB", x: 80, y: 75, label: "LB" },
    { id: "RM", x: 20, y: 55, label: "RM" },
    { id: "CM", x: 40, y: 55, label: "CM" },
    { id: "CM", x: 60, y: 55, label: "CM" },
    { id: "LM", x: 80, y: 55, label: "LM" },
    { id: "ST", x: 35, y: 30, label: "ST" },
    { id: "ST", x: 65, y: 30, label: "ST" },
  ],
  "4-2-3-1": [
    { id: "GK", x: 50, y: 95, label: "GK" },
    { id: "RB", x: 20, y: 75, label: "RB" },
    { id: "CB", x: 35, y: 75, label: "CB" },
    { id: "CB", x: 65, y: 75, label: "CB" },
    { id: "LB", x: 80, y: 75, label: "LB" },
    { id: "CDM", x: 35, y: 65, label: "CDM" },
    { id: "CDM", x: 65, y: 65, label: "CDM" },
    { id: "CAM", x: 50, y: 45, label: "CAM" },
    { id: "RM", x: 20, y: 35, label: "RM" },
    { id: "LM", x: 80, y: 35, label: "LM" },
    { id: "ST", x: 50, y: 20, label: "ST" },
  ],
  "3-5-2": [
    { id: "GK", x: 50, y: 95, label: "GK" },
    { id: "CB", x: 25, y: 75, label: "CB" },
    { id: "CB", x: 50, y: 75, label: "CB" },
    { id: "CB", x: 75, y: 75, label: "CB" },
    { id: "RWB", x: 15, y: 55, label: "RWB" },
    { id: "LWB", x: 85, y: 55, label: "LWB" },
    { id: "CM", x: 35, y: 55, label: "CM" },
    { id: "CM", x: 50, y: 55, label: "CM" },
    { id: "CM", x: 65, y: 55, label: "CM" },
    { id: "ST", x: 35, y: 25, label: "ST" },
    { id: "ST", x: 65, y: 25, label: "ST" },
  ],
  "4-1-2-1-2": [
    { id: "GK", x: 50, y: 95, label: "GK" },
    { id: "RB", x: 20, y: 75, label: "RB" },
    { id: "CB", x: 35, y: 75, label: "CB" },
    { id: "CB", x: 65, y: 75, label: "CB" },
    { id: "LB", x: 80, y: 75, label: "LB" },
    { id: "CDM", x: 50, y: 70, label: "CDM" },
    { id: "RM", x: 20, y: 50, label: "RM" },
    { id: "LM", x: 80, y: 50, label: "LM" },
    { id: "CAM", x: 50, y: 40, label: "CAM" },
    { id: "ST", x: 35, y: 20, label: "ST" },
    { id: "ST", x: 65, y: 20, label: "ST" },
  ],
};

// Match events data for timeline
export const matchEvents = [
  {
    time: 15,
    type: "goal",
    team: "team_a",
    player: "Harry Kane",
    description: "Great finish from outside the box",
  },
  {
    time: 23,
    type: "yellow_card",
    team: "team_b",
    player: "N'Golo Kanté",
    description: "Late challenge",
  },
  {
    time: 34,
    type: "goal",
    team: "team_a",
    player: "Son Heung-min",
    description: "Header from corner",
  },
  {
    time: 45,
    type: "substitution",
    team: "team_b",
    playerOut: "Erling Haaland",
    playerIn: "Karim Benzema",
    description: "Tactical change",
  },
  {
    time: 52,
    type: "goal",
    team: "team_b",
    player: "Kylian Mbappé",
    description: "Counter attack goal",
  },
  {
    time: 67,
    type: "substitution",
    team: "team_a",
    playerOut: "Joshua Kimmich",
    playerIn: "Declan Rice",
    description: "Injury replacement",
  },
  {
    time: 72,
    type: "yellow_card",
    team: "team_a",
    player: "Virgil van Dijk",
    description: "Professional foul",
  },
  {
    time: 82,
    type: "substitution",
    team: "team_b",
    playerOut: "Theo Hernandez",
    playerIn: "Antonio Rudiger",
    description: "Defensive reinforcement",
  },
  {
    time: 89,
    type: "red_card",
    team: "team_b",
    player: "Marquinhos",
    description: "Second yellow card",
  },
];

export default {
  enhancedPlayers,
  initialLineups,
  initialSubstitutes,
  formationPositions,
  matchEvents,
};
